### ISSUE TITLE
wrong aspect ratio, no subtitles and no context menu in MP MyAnime 3.6.0.4

### ISSUE THREAD

**Issue by Terr4** [japanesemediamanager/MyAnime3#31]
When playing an episode through the MyAnime 3.6.0.4 plugin in Media Portal 1.15 I get following issues:

- the aspect ratio of the playback is wrong, in my case it was always 4:3
- no subtitles are getting displayed as defined in preferences and cannot be enabled manually as it seems
- I cannot open the context menu in MP where you usually can set subtitles and aspect ratio. IR Remote shortcuts work for aspect ratio although.

The issues can be resolved by disabling "Streaming" in the plugin options in the MP Configuration for the MyAnime 3 plugin.

I can provide logs if that is needed. However I thought as the file actually plays and the streaming feature is new this is maybe more of a missing feature/work in progress topic.

thx for all the effort :)

**Comment by ElementalCrisis** [comment]
We also discovered this and it will be looked into.

**Comment by maxpiva** [comment]
Enabling Automatic filter selection in MediaPortal Configuration -> Codecs & Renderer 
will **fix it**. We're in the process of identifying the problem, which is Directshow filter related.

**Comment by maxpiva** [comment]
The fix for the 4:3 problem, since Streaming will be automatically enabled in next version, if you dont have you import folder mapped in My Anime. Or the Anime is in Cloud Storage:  

1) Install Lav Filters or any url filters with directshow merits, without a suitable Url filter, the video won't load.  #28.

2) Currently we have a bug with MediaPortal custom directshow graph build, If MediaPortal generates the directshow graph build, Aspect ratio got disorted. To fix this 
**Go to MediaPortal configuration->Codecs & Renderer -> Make sure Automatic decoder selection is checked.**
