### ISSUE TITLE
Anime3 start page (Titan) has no text background, is hard to read.

### ISSUE THREAD

**Issue by Andy2244** [japanesemediamanager/MyAnime3#33]
My Anime3 startup page is now hard to read, because the text elements have no background? The sub-pages look normal.

My Anime3 startup page looks like this:
![anime3](https://cloud.githubusercontent.com/assets/5340247/18230790/503f48f4-72a6-11e6-9ae1-afc6bf512df3.jpg)

**Comment by ElementalCrisis** [comment]
I suppose this is a good as spot as any to jump and and figure out how MediaPortal skins work.

**Comment by Terr4** [comment]
Did you do an update or a fresh install? I also use Titan and I don't have this problem:

![bildschirmfoto 2016-09-04 um 15 46 47](https://cloud.githubusercontent.com/assets/6331473/18231308/1c895c82-72b7-11e6-8530-26041ad75fdc.png)

**Comment by Andy2244** [comment]
I did upgrade/repair MP than a uninstall + install of MyAnime3.

**Comment by RickDB** [comment]
@Andy2244 Can't reproduce that problem here, could you check this folder:

C:\ProgramData\Team MediaPortal\MediaPortal\skin\Titan\Media

And see if you have the following files there:

panel_list.png
panel_list_noinfo.png

If so please try to clear the skin cache as there could be some leftover files, most skins have an option for that but you can also do this manually by **only** deleting the contents of this folder:

C:\ProgramData\Team MediaPortal\MediaPortal\Cache\

If you don't have those please reinstall Mediaportal 1.15 and check afterwards.

**Comment by Andy2244** [comment]
Both files are present and look fine, but even after deleting the cache i get the same problem. I will try the fresh install later this week and see if this solves it. Thanks for the time trying to solve this minor problem.

**Comment by RickDB** [comment]
Noticed that 1 file is missing (panel_myfilms_menu.png) and is only part of Titan extended, Moving Pictures might reference it as but you can get the it by installing Titan Extended:

http://www.team-mediaportal.com/extensions/widescreen/titan-extended

**Comment by Andy2244** [comment]
Installing Titan extended solved the problem for Anime3 and Moving Pictures, thx.

**Comment by RickDB** [comment]
Good to hear, missing file should be included in the next MA3 release as well :)
